:feelpp: Feel++
:cpp: C++
:project: 2023-m2-feelpp-sonorhc 

= {feelpp} Template Project 
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>
v2: 

## Dynamic Linear Elasticity

One part of this repository is the implementation of the dynamic linear elasticity problem. The mathematical framework as well as the explanation concerning the implementation are visible on the internet page linked to this repo (cf link on the right).

In other to reproduce the results, one can launch the following commands from the project's root after building it:
```bash
cd build/default/src &&
./feelpp_fs_elasticity --config-file ../../../src/cases/elastic/elastic.cfg
```

This will launch the 2D case. In order to change to the 3D implementation of the physical test led by sonorhc, one will have to change the following line in the `elastic.json` configuration file to pivot onto the right .geo file:

```json
"Meshes": {
    "elastic": {
        "Import": {
            "filename": "$cfgdir/square.geo",
            "partition": 0,
            "h": 0.02
        }
    }
}
```

has to be changed into :

```json
"Meshes": {
    "elastic": {
        "Import": {
            "filename": "$cfgdir/plaque.geo",
            "partition": 0,
            "h": 0.02
        }
    }
}
```

And the following constant also has to be changed from:
```cpp
inline const int FEELPP_DIM=2;
inline const int FEELPP_ORDER=2;
```
to
```cpp
inline const int FEELPP_DIM=3;
inline const int FEELPP_ORDER=2;
```

After execution (using the same commands as before), the results are stored in the feelpp database as an ensight folder, which location is printed in the terminal at the end of the execution, which can be visualized using Paraview and its `Glyph` or `Warp by Vector` filters (Filters -> Alphabetical -> Glyph or Warp by Vector ).
