site:
  title: 2023 M2 Feelpp Sonorhc
  url: https://feelpp.github.io/2023-m2-feelpp-sonorhc/
  start_page: 2023-m2-feelpp-sonorhc::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  supplemental_files: ./docs/antora/supplemental-ui
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  extensions:
  - '@feelpp/asciidoctor-extensions'
